/*
Copyright (c) 2010, Yahoo! Inc. All rights reserved.
Code licensed under the BSD License:
http://developer.yahoo.com/yui/license.html
version: 3.3.0
build: 3167
*/
YUI.add("event-simulate",function(a){(function(){var k=a.Lang,j=a.Array,f=k.isFunction,d=k.isString,g=k.isBoolean,o=k.isObject,n=k.isNumber,m=a.config.doc,p={click:1,dblclick:1,mouseover:1,mouseout:1,mousedown:1,mouseup:1,mousemove:1},l={keydown:1,keyup:1,keypress:1},c={blur:1,change:1,focus:1,resize:1,scroll:1,select:1},e={scroll:1,resize:1,reset:1,submit:1,change:1,select:1,error:1,abort:1};a.mix(e,p);a.mix(e,l);function i(v,z,u,s,B,r,q,A,x,D,C){if(!v){a.error("simulateKeyEvent(): Invalid target.");}if(d(z)){z=z.toLowerCase();switch(z){case"textevent":z="keypress";break;case"keyup":case"keydown":case"keypress":break;default:a.error("simulateKeyEvent(): Event type '"+z+"' not supported.");}}else{a.error("simulateKeyEvent(): Event type must be a string.");}if(!g(u)){u=true;}if(!g(s)){s=true;}if(!o(B)){B=window;}if(!g(r)){r=false;}if(!g(q)){q=false;}if(!g(A)){A=false;}if(!g(x)){x=false;}if(!n(D)){D=0;}if(!n(C)){C=0;}var y=null;if(f(m.createEvent)){try{y=m.createEvent("KeyEvents");y.initKeyEvent(z,u,s,B,r,q,A,x,D,C);}catch(w){try{y=m.createEvent("Events");}catch(t){y=m.createEvent("UIEvents");}finally{y.initEvent(z,u,s);y.view=B;y.altKey=q;y.ctrlKey=r;y.shiftKey=A;y.metaKey=x;y.keyCode=D;y.charCode=C;}}v.dispatchEvent(y);}else{if(o(m.createEventObject)){y=m.createEventObject();y.bubbles=u;y.cancelable=s;y.view=B;y.ctrlKey=r;y.altKey=q;y.shiftKey=A;y.metaKey=x;y.keyCode=(C>0)?C:D;v.fireEvent("on"+z,y);}else{a.error("simulateKeyEvent(): No event simulation framework present.");}}}function b(A,F,x,u,G,z,w,v,t,r,s,q,E,C,y,B){if(!A){a.error("simulateMouseEvent(): Invalid target.");}if(d(F)){F=F.toLowerCase();if(!p[F]){a.error("simulateMouseEvent(): Event type '"+F+"' not supported.");}}else{a.error("simulateMouseEvent(): Event type must be a string.");}if(!g(x)){x=true;}if(!g(u)){u=(F!="mousemove");}if(!o(G)){G=window;}if(!n(z)){z=1;}if(!n(w)){w=0;}if(!n(v)){v=0;}if(!n(t)){t=0;}if(!n(r)){r=0;}if(!g(s)){s=false;}if(!g(q)){q=false;}if(!g(E)){E=false;}if(!g(C)){C=false;}if(!n(y)){y=0;}B=B||null;var D=null;if(f(m.createEvent)){D=m.createEvent("MouseEvents");if(D.initMouseEvent){D.initMouseEvent(F,x,u,G,z,w,v,t,r,s,q,E,C,y,B);}else{D=m.createEvent("UIEvents");D.initEvent(F,x,u);D.view=G;D.detail=z;D.screenX=w;D.screenY=v;D.clientX=t;D.clientY=r;D.ctrlKey=s;D.altKey=q;D.metaKey=C;D.shiftKey=E;D.button=y;D.relatedTarget=B;}if(B&&!D.relatedTarget){if(F=="mouseout"){D.toElement=B;}else{if(F=="mouseover"){D.fromElement=B;}}}A.dispatchEvent(D);}else{if(o(m.createEventObject)){D=m.createEventObject();D.bubbles=x;D.cancelable=u;D.view=G;D.detail=z;D.screenX=w;D.screenY=v;D.clientX=t;D.clientY=r;D.ctrlKey=s;D.altKey=q;D.metaKey=C;D.shiftKey=E;switch(y){case 0:D.button=1;break;case 1:D.button=4;break;case 2:break;default:D.button=0;}D.relatedTarget=B;A.fireEvent("on"+F,D);}else{a.error("simulateMouseEvent(): No event simulation framework present.");}}}function h(w,v,s,r,q,u){if(!w){a.error("simulateUIEvent(): Invalid target.");}if(d(v)){v=v.toLowerCase();if(!c[v]){a.error("simulateUIEvent(): Event type '"+v+"' not supported.");}}else{a.error("simulateUIEvent(): Event type must be a string.");}var t=null;if(!g(s)){s=(v in e);}if(!g(r)){r=(v=="submit");}if(!o(q)){q=window;}if(!n(u)){u=1;}if(f(m.createEvent)){t=m.createEvent("UIEvents");t.initUIEvent(v,s,r,q,u);w.dispatchEvent(t);}else{if(o(m.createEventObject)){t=m.createEventObject();t.bubbles=s;t.cancelable=r;t.view=q;t.detail=u;w.fireEvent("on"+v,t);}else{a.error("simulateUIEvent(): No event simulation framework present.");}}}a.Event.simulate=function(s,r,q){q=q||{};if(p[r]){b(s,r,q.bubbles,q.cancelable,q.view,q.detail,q.screenX,q.screenY,q.clientX,q.clientY,q.ctrlKey,q.altKey,q.shiftKey,q.metaKey,q.button,q.relatedTarget);}else{if(l[r]){i(s,r,q.bubbles,q.cancelable,q.view,q.ctrlKey,q.altKey,q.shiftKey,q.metaKey,q.keyCode,q.charCode);}else{if(c[r]){h(s,r,q.bubbles,q.cancelable,q.view,q.detail);}else{a.error("simulate(): Event '"+r+"' can't be simulated.");}}}};})();},"3.3.0",{requires:["event-base"]});
/*
Copyright (c) 2010, Yahoo! Inc. All rights reserved.
Code licensed under the BSD License:
http://developer.yahoo.com/yui/license.html
version: 3.3.0
build: 3167
*/
YUI.add("node-event-simulate",function(a){a.Node.prototype.simulate=function(c,b){a.Event.simulate(a.Node.getDOMNode(this),c,b);};},"3.3.0",{requires:["node-base","event-simulate"]});
YUI.add("zillow-imageupload",function(c){var e="ImageUpload",m="debug",d="info",g="error",j="src",k=".preview-images",h="li",f="waiting",i=h+"."+f,b=c.config.win;
var a={},l=null,n=0;a.uploadURL="/app?service=imaging";a.init=function(){var D=c.one(k),x=D.all(h),L="mainImage",o=30,q=2000,z=2,O=20000,J="BLARGfatz123",s={},u=null,B=function(){var T=u;
if(T===null){var S=c.one(".image-upload-div iframe")._node;if(S){S=S.contentDocument||S.contentWindow.document||S.document;
if(S){T=u=S.forms[0];}}}return T;},C=(B().singleUpload&&B().singleUpload.value.toLowerCase()==="true"),N=D.ancestor(".generic-toolbar")!==null,F=null,K='Please select a file by clicking "Browse"';
var H=c.one(".maxUploadLimit");if(H!=null&&H.get("value")){l=H.get("value");}function y(S){if(S&&S.value){return false;
}else{return true;}}var I={add:function(T){var S=T+"&ts="+(new Date().getTime());c.log("add "+S,d,"CacheBuster");
return S;},remove:function(T){var S=T.substring(0,T.indexOf("&ts="));c.log("remove "+S,d,"CacheBuster");
return S;}};function G(){c.all("#uploaderror").remove(true);}a.error=function(S){var T=c.one("#disclaimer");
if(T===null){T=c.one(".image-upload-div").get("parentNode");}G();if(S){c.message(S,"error");T.append('<div id="uploaderror" class="message-bar error">'+S+"</div>");
a.onError.fireEvent(S);}};a.onComplete=new Subscriber();a.onError=new Subscriber();function r(S,T){c.log("makeResponseHandler creating closure",m,e);
return function(W){try{if(W.type==="load"){return;}var U=W.responseText.replace(/<\/?pre.*?>/ig,"");if(c.one("#ad-preview")!==null){U=U.replace("size%3D100%2C100","wid%3D130%26hei%3D65");
}c.log("response text -> "+U,m,e);W=c.JSON.parse(U);if(W&&W.errorMessage){throw (W.errorMessage);}if(S){S(W);
}}catch(V){if(T){T(V);}else{a.error(V);}}};}a.request=function(T,U){G();T.contextId=c.one("#contextId").get("value");
c.log("making request "+T.operation,m,e);try{c.io(a.uploadURL,{method:"POST",data:T,on:{success:function(W,V){if(U.success){U.success(V);
}},failure:function(W,V){if(U.failure){U.failure(V);}}}});}catch(S){c.error("Error making ImageUpload request",S);
}};function P(S,U,T){log("imgReload",S,U,T);return function(V){log(V);c.log("imgReload handling "+V.type,m,e);
if(U===b.location||U.indexOf(J)>-1){c.log("???loaded "+U,m,e);}s[U]=s[U]||{to:0,imgtries:0};s[U].to=setTimeout(function(){c.Event.purgeElement(S,false,g);
if(s[U].imgtries===undefined){s[U].imgtries=0;}else{if(s[U].imgtries>=o){s[U].imgtries=0;log("error loading",U);
return;}}c.on(g,P(S,U,Math.min(T*z,O)),S);log("still loading",S);c.log("imgReload still loading\n"+U,m,e);
s[U].imgtries++;try{var X=I.add(U);if(c.UA.ie&&c.UA.ie<8){var Y=S.get("parentNode");S.remove().set(j,J).appendTo(Y).set(j,X);
}else{S.set(j,X);}}catch(W){}},T);};}function t(S,T,U){return function(){c.log("imgLoad "+U+"\n"+T,m,e);
if(T===b.location||T.indexOf(J)>-1){return;}S.purge();if(s[T]&&s[T].to!==undefined){clearTimeout(s[T].to);
s[T].imgtries=0;}var V=I.remove(S.get(j));c.log("imgLoad finished loading?\n"+V,m,e);S.siblings(".indicator").remove(true);
S.ancestor(h).removeClass(f);try{if(c.UA.ie===6){a.onComplete.fireEvent([V,U]);S.show();}else{var X=c.Node.create('<img src="'+I.add(T)+'" />');
c.on(g,P(X,T,100),X);S.replace(X);}}catch(W){log(S);log(W);}if(!a.onComplete.hasFired){a.onComplete.fireEvent([V,U]);
}};}function p(){if(F===null){F=x.pop().remove().removeClass("hide");F.all("input").set("value","");F.all("select").set("selectedIndex",0);
}return F.cloneNode(true);}function E(){var S=p(),T=c.one(".firstImage");if(T.hasClass("hide")||x.refresh().size()===0){T.show();
S.addClass(L);}D.append(S);}function R(T){var U=T.imageId,W=D.one(i).set("id",U),S=W.one("img.thumbnail"),V=decodeURIComponent(T.imageURL);
c.log("populateTemplate src\n"+V,m,e);S.setAttribute("alt",V);s[V]={to:0,imgtries:0};a.onComplete.hasFired=false;
c.on("load",t(S,V,U),S);c.on(g,P(S,V,q),S);S.set(j,I.add(V));if(C){c.all("#single-image-removed").set("value",0);
c.all("#single-image-remove-button").show();}}function v(){E();c.log("Creating responseHandler",m,e);
return r(function(S){if(l){c.log("Incrementing upload count from "+n+" by one.",m,e);n++;if(n>=l){M(false);
}}c.log("upload responseHandler setting timeout for "+S.imageId,m,e);setTimeout(function(){R(S);},1000);
},function(S){a.error(S);D.all(i).remove(true);});}function A(){return function(T){c.all(".initialImage").hide();
x.refresh().each(function(V){V.purge();var W=s[V.get(j)];if(W){clearTimeout(W.to);}V.remove(true);});
E();R(T);try{var S=c.all("div.no-image");if(S.size()>0){S.item(0).removeClass("no-image");}}catch(U){log(U);
}};}a.upload=function(){var T=B();if(y(T.image)){a.error(K);return false;}G();var S;if(C){S=r(A());}else{S=v();
}c.log("uploading","warn",e);c.io(a.uploadURL,{method:"POST",form:{id:T,useDisabled:true,upload:true},on:{complete:function(V,U){if(S){S(U);
}}}});return false;};a.setCaption=function(T,S){a.request({operation:"setImageCaption",imageId:T,service:"imaging",caption:S},{success:r(null,function(Y){var X=c.one("#"+T).one("input[type=text]").set("value","").get("region"),W="top:"+(X.top+20)+"px;",V="left:"+X.left+"px;",U=c.Node.create('<p class="captionerror" style="'+W+V+'">'+Y+"</p>");
c.one("body").append(U);setTimeout(function(){U.remove(true);},3000);}),failure:r()});};a._doCategoryRequest=function(T,S){T.cid=c.one("#contextId").get("value");
c.io("/homeimprovement/duel/DuelUploadChangeCategoryAjaxPage.htm",{method:"POST",data:T,on:{success:function(){c.log(S+" image category",d);
},failure:function(){c.log(S+" image category failed",g);}}});};a.setCategory=function(S,T){a._doCategoryRequest({zdc:T,zid:S,zop:"add"},"changed");
};a.removeCategory=function(S){a._doCategoryRequest({zdc:"",zid:S,zop:"remove"},"removed");};function Q(S){return function(){c.one(S).remove(true);
if(l){c.log("Decrementing upload count from "+n+" by one.",m,e);n--;if(n<l){M(true);}}var T=x.refresh();
if(T.size()){T.item(0).addClass(L);}};}function M(T){var U=B();if(U&&T!=null){var V=c.one(U),S=V.one("button");
if(S){if(T){S.removeAttribute("disabled").blur();}else{S.setAttribute("disabled","true");}S[(T?"remove":"add")+"Class"]("disabled");
}}}a.remove=function(T){c.log("removing "+T,m,e);var S=c.one("#"+T).hide();if(x.refresh().size()<=1){c.one(".firstImage").hide();
}a.request({operation:"removeImage",service:"imaging",imageId:T},{success:r(Q(S)),failure:r(function(U){a.error(U);
S.show();})});if(C){c.all("#single-image-removed").set("value",1);c.all("#single-image-remove-button").hide();
}};if(N){return;}function w(U){var T=U.target,V=T.get("nodeName").toLowerCase(),S=T.ancestor("li").get("id");
switch(V){case"a":U.halt();a.remove(S);a.removeCategory(S);break;case"input":a.setCaption(S,T.get("value"));
break;case"select":a.setCategory(S,T.get("value"));break;}}D.delegate("change",w,"input.caption");D.delegate("change",w,"select.category");
D.delegate("click",w,"a.remove");c.on("key",function(S){S.halt();},".preview-images .caption","down:13");
if(!C){c.log("plugging dragdrop",m,e);c.use("dd","dd-drop-plugin",function(S){var aa,W="ddcurrent",T="ddtarget",U="node",X={success:r(),failure:log};
function ab(ac){var Y=ac.target.get(U);if(ac.type==="drag:start"){Y.addClass(W);}else{Y.removeClass(W);
}}function Z(ac){var Y=ac.target.get(U);if(ac.type==="drop:enter"){Y.addClass(T);}else{Y.removeClass(T);
}}function V(af){var ae=af.drag.get(U),ad=af.drop.get(U),Y=S.all(k+" "+h+'[id^="X"]'),ac=Y.indexOf(ad)>Y.indexOf(ae)?"after":"before";
S.log("inserting dragged node "+ac+" drop target",d,e);ad.insert(ae,ac);Y.refresh().removeClass(L).item(0).addClass(L);
a.request({operation:"updateImageOrder",service:"imaging",ordering:Y.get("id").join(",")},X);}aa=new S.DD.Delegate({container:k,nodes:h,target:true,on:{"drag:start":ab,"drag:end":ab,"drag:drophit":V,"drop:enter":Z,"drop:exit":Z,"drop:hit":Z},invalid:".caption"});
aa.dd.plug(S.Plugin.DDConstrained,{constrain:k}).plug(S.Plugin.DDProxy,{cloneNode:true,moveOnEnd:false});
a.onComplete.subscribe(function(){aa.syncTargets();});});}};b.ImageUpload=a;},"3.3.0",{requires:["zillow-node-methods","io-form","io-upload-iframe","json-parse","node-event-delegate","event-key"],optional:["dd","dd-drop-plugin"]});
YUI.add("zillow-richtexteditor",function(e){var d=e.namespace("Z"),c="debug",b={Advice:{collapse:false,titlebar:"Text Editing Tools",draggable:false,buttonType:"basic",buttons:[{group:"textstyle",buttons:[{type:"push",label:"Bold CTRL + SHIFT + B",value:"bold"},{type:"push",label:"Italic CTRL + SHIFT + I",value:"italic"},{type:"push",label:"Underline CTRL + SHIFT + U",value:"underline"}]},{type:"separator"},{group:"alignment",buttons:[{type:"push",label:"Align Left CTRL + SHIFT + [",value:"justifyleft"},{type:"push",label:"Align Center CTRL + SHIFT + |",value:"justifycenter"},{type:"push",label:"Align Right CTRL + SHIFT + ]",value:"justifyright"},{type:"push",label:"Justify",value:"justifyfull"}]},{type:"separator"},{group:"insertitem",buttons:[{type:"push",label:"HTML Link CTRL + SHIFT + L",value:"createlink",disabled:true},{type:"push",label:"Insert Image",value:"insertimage"}]},{type:"separator"},{group:"undoredo",buttons:[{type:"push",label:"Undo",value:"undo",disabled:true},{type:"push",label:"Redo",value:"redo",disabled:true}]}]},Profile:{collapse:false,titlebar:"Text Editing Tools",draggable:false,buttonType:"basic",buttons:[{group:"insertitem",buttons:[{type:"push",label:"HTML Link CTRL + SHIFT + L",value:"createlink",disabled:true}]}]},Default:{collapse:false,titlebar:"Text Editing Tools",draggable:false,buttonType:"advanced",buttons:[{group:"textstyle",buttons:[{type:"push",label:"Bold CTRL + SHIFT + B",value:"bold"},{type:"push",label:"Italic CTRL + SHIFT + I",value:"italic"},{type:"push",label:"Underline CTRL + SHIFT + U",value:"underline"},{type:"separator"},{type:"push",label:"Remove Formatting",value:"removeformat",disabled:true}]},{type:"separator"},{group:"alignment",buttons:[{type:"push",label:"Align Left CTRL + SHIFT + [",value:"justifyleft"},{type:"push",label:"Align Center CTRL + SHIFT + |",value:"justifycenter"},{type:"push",label:"Align Right CTRL + SHIFT + ]",value:"justifyright"},{type:"push",label:"Justify",value:"justifyfull"}]},{type:"separator"},{group:"undoredo",buttons:[{type:"push",label:"Undo",value:"undo",disabled:true},{type:"push",label:"Redo",value:"redo",disabled:true}]},{type:"separator"},{group:"parastyle",buttons:[{type:"select",label:"Normal",value:"heading",disabled:true,menu:[{text:"Normal",value:"none",checked:true},{text:"Header 1",value:"h1"},{text:"Header 2",value:"h2"},{text:"Header 3",value:"h3"},{text:"Header 4",value:"h4"},{text:"Header 5",value:"h5"},{text:"Header 6",value:"h6"}]}]},{type:"separator"},{group:"indentlist",buttons:[{type:"push",label:"Indent",value:"indent",disabled:true},{type:"push",label:"Outdent",value:"outdent",disabled:true},{type:"push",label:"Create an Unordered List",value:"insertunorderedlist"},{type:"push",label:"Create an Ordered List",value:"insertorderedlist"}]},{type:"separator"},{group:"insertitem",buttons:[{type:"push",label:"HTML Link CTRL + SHIFT + L",value:"createlink",disabled:true},{type:"push",label:"Insert Image",value:"insertimage"},{type:"push",label:"Insert Video",value:"insertvideo"}]}]}};
function a(g){var h=this.id=g.id;this.config=g||{};this.editorActive=false;var k=false;if(this.config.focus){k=true;
}var j=this.config.toolbar||"Default";log("using toolbar: "+j);var f=(j==="Default")?"Editor":"SimpleEditor";
this.editor=new e.YUI2.widget[f]("rte-"+h,{height:this.config.editorDim.height+"px",width:this.config.editorDim.width+"px",dompath:true,filterWord:true,focusAtStart:k,extracss:"img.rte-video { height: 344px; width: 425px; background: #aaa; display: block; }",toolbar:b[j]});
this.selectedLinkText=null;this.editingRawHTML=false;this.allowImages=true;var i=this;this.editor.on("toolbarLoaded",function(){if(!this.toolbar.getButtonByValue("insertimage")){this.invalidHTML.img=true;
i.allowImages=false;}this.toolbar.on("insertimageClick",function(m){this.showImagePanel();return false;
},i,true);this.toolbar.on("insertvideoClick",function(m){this.showVideoPanel();return false;},i,true);
this.toolbar.on("createlinkClick",function(n,s){try{if(s.name!=="zLink"){log("not our call");return false;
}if(this.isPanelVisible(this.linkPanel)){return false;}var o=this.editor.currentElement[0];var r;this.hasSelectedText=this.editor._hasSelection();
if(o&&this.hasSelectedText){var p=o.innerHTML;var m=this.editor._getSelection();if(p===m){this.hasSelectedImage=o.tagName==="IMG";
this.hasSelectedLink=o.tagName==="A";if(this.hasSelectedLink){r=o.getAttribute("href");}}}this.selectedRange=this.editor._getRange();
e.log("tag selected -> "+(o?("tagName: "+o.tagName+" Text: "+o.innerHTML):"no tag selected"),c,this);
e.log("selected text: -> "+this.hasSelectedText,c,this);e.log("this.hasSelectedImage -> "+this.hasSelectedImage,c,this);
e.log("this.hasSelectedLink  -> "+this.hasSelectedLink,c,this);e.log(this.selectedRange);this.showLinkPanel(r);
}catch(q){log("link click failed",q);}return false;},{name:"zLink"},i);if(i.config.isAdmin){var l={type:"push",label:"Edit HTML Code",value:"editcode"};
this.toolbar.addButtonToGroup(l,"insertitem");this.toolbar.on("editcodeClick",function(){var m=this.get("element"),n=this.get("iframe").get("element");
if(i.editingRawHTML){i.editingRawHTML=false;log("hiding raw HTML editor",i);this.editorDirty=true;this.setEditorHTML(m.value);
if(!this.browser.ie){this._setDesignMode("on");}this.toolbar.set("disabled",false);e.one(n).removeClass("editor-hidden");
e.one(m).addClass("editor-hidden");this.show();this.focus();}else{i.editingRawHTML=true;log("showing raw HTML editor",i);
this.cleanHTML();e.one(n).addClass("editor-hidden");e.one(m).removeClass("editor-hidden");this.toolbar.set("disabled",true);
this.toolbar.getButtonByValue("editcode").set("disabled",false);this.toolbar.selectButton("editcode");
this.dompath.innerHTML="Editing HTML Code";this.hide();}return false;},this,true);this.on("cleanHTML",function(m){this.get("element").value=m.html;
},this,true);this.on("afterRender",function(){var m=this.get("editor_wrapper");m.appendChild(this.get("element"));
this.setStyle("width","100%");this.setStyle("height","100%");this.setStyle("visibility","");this.setStyle("top","");
this.setStyle("left","");this.setStyle("position","");this.addClass("editor-hidden");},this,true);}},this.editor,true);
this.editor.on("editorKeyPress",function(l){this.editorDirty=true;},this.editor,true);this.setupPasteOverride();
if(this.config.initOnLoad){e.on("domready",this.edit,this);}this.onEdit=new Subscriber("onEdit");this.onSave=new Subscriber("onSave");
this.onCloseEditor=new Subscriber("onCloseEditor");this.onEditorLoadComplete=new Subscriber("onEditorLoadComplete");
this.onAfterLinkPanelCreation=new Subscriber("onAfterLinkPanelCreation");e.fire("editor:loaded",this);
}a.separator={attr:"\01",keyVal:"\02"};a.RE={smartDouble:new RegExp("["+String.fromCharCode(8220)+String.fromCharCode(8221)+"]","g"),smartSingle:new RegExp(String.fromCharCode(8217),"g"),unknownChar:new RegExp(String.fromCharCode(65533),"g")};
a.prototype={constructor:a,toString:function(){return"RichTextEditor["+this.id+"]";},renderZillowEditor:function(){var g=this;
var f=e.one("#rte-"+this.id).ancestor("form");if(f){f.addClass("rich-text");f.on("submit",this.onParentFormSubmit,this);
e.fire("editor:hookForm",{id:this.id,form:f});}this.editor.on("editorContentLoaded",function(i,k){try{log("editorContentLoaded");
var h=g.getViewRegion().get("innerHTML");g.setHTML(e.Lang.isValue(h)?h:"");if(Element.isVisible("editorViewRegion"+g.id)){g.makeVisible("editorEditRegion");
g.showEditor();}g.resetIsDirty();g.editorLoadComplete();}catch(j){log("Could not setup HTML: ",j);}},{isActive:this.editorActive},this.editor);
this.editor.render();this.hasRendered=true;},onParentFormSubmit:function(h){if(this.editorActive){e.log("onParentFormSubmit",c,this);
var f=h.target.one(".editor-source"),g=this.getHTML();if(f&&g){f.set("value",g);}}},showEditor:function(){this.displayNone("editorViewRegion");
this.display("editorEditRegion");this.editor.show();},closeUnderlyingEditor:function(){this.displayNone("editorEditRegion");
this.display("editorViewRegion");this.editor.hide();},getHTML:function(){try{var f="";try{f=this.editor.cleanHTML(f);
}catch(h){log("Editor hasnt loaded yet but submit pressed "+h);}f=this.filterText(f);f=this.filterImages(f);
if(f.match(/^(\s)*(<p>(&nbsp;|\s)*<\/p>|\s)+(\s)*$/)||f.length===0){f=" ";log("Content set to empty string");
}var i=Element.make("div");i.innerHTML=f;f=this.decodeVideos(i);return f;}catch(g){log("can't get html: ",g);
e.log("Can't get HTML: "+g.message,"error",this);return false;}},insertZillowImage:function(j,g,i){try{var f='<img src="'+j+'" imageid="'+g+'" uploadtype="new" imagetype="'+i+'" />';
this.editor.focus();this.editor.execCommand("inserthtml",f);return true;}catch(h){log("Could not insert image",h);
return false;}},insertVideo:function(f){try{e.log("insertVideo input: "+f,c,this);var i=Element.make("div");
i.innerHTML=f;var g=this.encodeVideo(i);log("Youtube embed: ",g);e.log("Embedding video:\n"+g,c,this);
if(!g){return false;}this.editor.focus();this.editor.execCommand("inserthtml",g);return true;}catch(h){log("Error: could not insert video:",h);
e.log("Could not insert video: "+h,"error",this);return false;}},insertZillowLink:function(g,j,f){if(this.selectedRange&&this.selectedRange.select&&this.hasSelectedText){if(this.selectedRange.text.lastIndexOf(" ")===(this.selectedRange.text.length-1)){this.selectedRange.moveEnd("character",-1);
}if(this.selectedRange.text.indexOf(" ")===0){this.selectedRange.moveStart("character",1);}this.selectedRange.select();
}if(this.hasSelectedText){try{if(!this.hasSelectedLink){this.editor.execCommand("createlink");}e.Array.forEach(this.editor.currentElement,function(k){k.setAttribute("href",g);
if(!f){k.setAttribute("rel","nofollow");}});e.log("insertZillowLink had selectedText, successfully inserted "+g,c,this);
}catch(h){log("Can not add link",h);}}else{var i='<a href="'+g+'"'+(f?"":' rel="nofollow"')+">"+j+"</a>";
this.editor.focus();this.editor.execCommand("inserthtml",i);e.log("insertZillowLink inserted HTML "+i,c,this);
}},resetIsDirty:function(){this.editor.editorDirty=false;},setHTML:function(g){var h=Element.make("div");
h.innerHTML=g;var f=h.getElementsByTagName("object");this.transformVideos(f);log(h.innerHTML);this.editor.setEditorHTML(h.innerHTML);
},isDirty:function(){return this.editor.editorDirty===true;},hasFocus:function(){},focusEditor:function(g){var f=this;
if(g){setTimeout(function(){f.editor.focus();},100);}else{f.editor.focus();}e.fire("editor:focused",f.editor);
},setupPasteOverride:function(){var f=this;this.ctrlKey=false;this.pasted=false;this.editor.on("editorKeyUp",function(g){try{if(g&&g.ev&&g.ev.keyCode===86&&f.pasted){f.pasted=false;
e.one(this._getDoc()).all("body").each(function(j){var i=e.Node.getDOMNode(j);f.cleanPastedContent(i);
});}if(g&&g.ev&&g.ev.keyCode===17){f.ctrlKey=false;}}catch(h){log("Error traversing through pasted content: ",h);
}},this.editor,true);this.editor.on("editorKeyDown",function(g){if(g&&g.ev&&g.ev.keyCode===17){f.ctrlKey=true;
}},this.editor,true);this.editor.on("editorKeyPress",function(g){try{if(g&&g.ev&&g.ev.charCode===118&&f.ctrlKey){f.pasted=true;
}}catch(h){log("error: ",h);}},this.editor,true);},cleanPastedContent:function(g){try{if(!g){return;}g.id="";
var f=g.innerHTML;f=this.editor.cleanHTML(f);g.innerHTML=this.filterText(f);}catch(h){log("Could not clean pasted content:",h);
}},getEditor:function(){return this.editor;},edit:function(){if(this.editorActive){return;}try{if(!this.hasRendered){this.renderZillowEditor();
}else{this.showEditor();}this.editorActive=true;}catch(f){log("can't edit!:",f);}this.doEdit();},saveSuccessful:function(g,f){this.updateView(g);
this.resetIsDirty();if(f!==undefined){this.setHTML(f);}this.closeEditor();},saveFailed:function(f){if(typeof f==="undefined"){return"Sorry, we were unable to save your changes. Please try again.";
}if(f.indexOf("newVersionAlreadyCreated")>=0){this.showConflictPanel();}else{var g=this.getErrorMessage(f);
if(g){this.showErrorMessage(g);}else{this.showErrorMessage("Sorry, we were unable to save your changes. Please try again.");
}}return true;},getImageContextId:function(){return $("image-context-id"+this.id).value;},save:function(){this.clearErrors();
this.contextId=this.getImageContextId();var f=this.getHTML();e.log("Saving HTML:\n"+f,"info",this);this.doSave(f,this.isDirty());
},cancel:function(){if(this.editorActive){var f=true;if(this.isDirty()){f=e.config.win.confirm("Really cancel? You'll lose your changes");
}if(f){this.closeEditor();this.resetData();this.resetIsDirty();}return f;}return true;},resetData:function(){this.setHTML(this.getViewRegion().get("innerHTML"));
},updateView:function(f){if(!f){f=this.getHTML();}e.log("updateView HTML:\n"+f,c,this);this.getViewRegion().setContent(f);
},getViewRegion:function(){return e.one("#editorViewRegion"+this.id+" #editorViewContent");},closeEditor:function(){this.closeUnderlyingEditor();
this.cancelLinkPanel();this.cancelImagePanel();this.clearErrors();this.editorActive=false;this.doCloseEditor();
},clearErrors:function(){Element.hide("richText-errors-"+this.id);},showVideoPanel:function(){if(this.isPanelVisible(this.videoPanel)){return;
}if(!this.videoPanel){this.videoPanel=new e.YUI2.widget.Panel("editorVideoPanelDiv"+this.id,{width:"60em",fixedcenter:false,constraintoviewport:true,close:true,visible:false,draggable:true,modal:false,context:["editorEditRegion"+this.id,"bl","tl"]});
this.videoPanel.beforeHideEvent.subscribe(function(){return false;},null,this);this.display("editorVideoPanelDiv");
this.videoPanel.render();this.videoPanel.align("bl","tl");this.bindZButton(this.videoPanel,"addVideo","closeVideoPanel");
}e.one($("editor-video-embed-error-"+this.id)).addClass("hide");this.videoPanel.show();},closeVideoPanel:function(){this.videoPanel.hide();
},addVideo:function(g){if(g){g.halt();}var f=$("editor-video-embed-"+this.id).value;if(!this.insertVideo(f)){e.one($("editor-video-embed-error-"+this.id)).removeClass("hide");
return;}this.closeVideoPanel();},transformVideos:function(g){var j,h=Element.make("div");for(var f=0;
f<g.length;f++){j=Element.setHTML(h,this.encodeVideo(g[f])).getElementsByTagName("img");if(j){g[f].parentNode.replaceChild(j[0],g[f]);
}}},decodeVideos:function(f){e.one(f).all("img.rte-video").each(function(l){var j=e.Node.getDOMNode(l);
log(j);var m=Element.make("Object");var p=Element.make("embed");var h=j.getAttribute("longdesc",2);var o=a.separator;
var k=h.split(o.attr);for(var n=0;n<k.length;n++){var q=k[n].split(o.keyVal);if(q.length==2){var g=q[0];
var r=q[1];if(q[0]!="width"&&q[1]!="height"){m.appendChild(Element.make("param",{name:(g=="src"?"movie":g),value:r}));
}p.setAttribute(g,r);}}m.appendChild(p);j.parentNode.replaceChild(m,j);});return f.innerHTML;},encodeVideo:function(g){var l=g.getElementsByTagName("embed")[0];
if(!l){e.log("in encodeVideo, typeof embed == "+(typeof l),"error",this);return"";}var h=[],f,k=a.separator;
for(var j=0;j<l.attributes.length;j++){f=l.attributes[j];h.push(f.name+k.keyVal+f.value);}return'<img longdesc="'+h.join(k.attr)+'" height="344" width="425" class="rte-video" />';
},showImagePanel:function(){try{log("opening the image panel");if(this.isPanelVisible(this.imagePanel)){return;
}if(!this.imagePanel){this.imagePanel=new e.YUI2.widget.Panel("editorImagePanelDiv"+this.id,{close:true,constraintoviewport:true,context:["editorEditRegion"+this.id,"bl","tl"],fixedcenter:false,modal:false,visible:false,width:"45em"});
this.imagePanel.hideEvent.subscribe(this.cancelImagePanel,null,this);this.display("editorImagePanelDiv");
this.imagePanel.render();this.imagePanel.align("bl","tl");this.bindZButton(this.imagePanel,"addImage","cancelImagePanel");
var k=this.id+"Upload",g=e.one("#"+k+"-wrap").getAttribute("url"),h=new e.Z.DeferredIframe({delay:0,id:k,height:90,width:340,url:g});
}this.imagePanel.show();var j=this.getImageUploadIframe();var f=j.getElementById("input_imgupload");if(f){f.focus();
}if(e.UA.ie&&!this.image_input){this.image_input=f.cloneNode(true);}}catch(i){log(i);}},getImageUploadIframe:function(){var f=$(this.imagePanel.id).getElementsByTagName("iframe");
var j=null,g,h,k=this.id+"Upload";for(g=0;g<f.length;g++){h=f[g];if(h.id===k){j=h.contentDocument||h.contentWindow.document;
return j;}}return j;},addImage:function(g){if(g){g.halt();}if(!$("image-disclaimer-checkbox-"+this.id).checked){Element.show("image-disclaimer-error-"+this.id);
return;}else{Element.hide("image-disclaimer-error-"+this.id);}try{this.subscribeToImageLoad();Element.show("image-upload-throbber"+this.id);
ImageUpload.upload();}catch(h){try{if(h&&h.message.length>0){e.one("#disclaimer").append('<div id="uploaderror" class="message-bar error">'+h.message+"</div>");
}}catch(f){}this.imageUploadError(h);}},imageUploadError:function(f){this.unsubscribeToImageLoad();Element.hide("image-upload-throbber"+this.id);
},imageUploaded:function(q){var f=q[0],h=q[1],r=e.merge,i=e.QueryString,o=i.stringify;var m=f.split("?");
var k=i.parse(m[1]);delete k.hei;delete k.wid;m[1]=o(k);f=m.join("?");var j=$("richtext-image-type-"+this.id).value;
var p=this;var g=p.config.imageDim;var n=new Image();var l=function(u){e.log("imageUploaded setSizeAndInsert ("+u.type+")",c,p);
var s=n,v=s.height,t=s.width;if(v>g.height||t>g.width){v=g.height;t=g.width;}m[1]=o(r(k,{size:t+","+v})).replace(/%2C/g,",");
p.insertImage(m.join("?"),h,j);};e.on("load",l,n);e.on("error",l,n);n.src=f;},insertImage:function(h,f,g){this.insertZillowImage(h,f,g);
this.unsubscribeToImageLoad();Element.hide("image-upload-throbber"+this.id);this.closeImagePanel();},subscribeToImageLoad:function(){ImageUpload.onComplete.subscribe(this.imageUploaded,this);
ImageUpload.onError.subscribe(this.imageUploadError,this);},unsubscribeToImageLoad:function(){ImageUpload.onComplete.unsubscribe(this.imageUploaded,this);
ImageUpload.onError.unsubscribe(this.imageUploadError,this);},closeImagePanel:function(){this.imagePanel.hide();
ImageUpload.error("");$("image-disclaimer-checkbox-"+this.id).checked=false;Element.hide("image-disclaimer-error-"+this.id);
Element.hide("image-upload-throbber"+this.id);var h=this.getImageUploadIframe();this.unsubscribeToImageLoad();
if(h===null){return;}var g=h.getElementById("input_imgupload");if(this.image_input){var f=g.parentNode;
f.replaceChild(this.image_input.cloneNode(true),g);}else{g.value="";}},cancelImagePanel:function(){if(!this.imagePanel){return;
}this.closeImagePanel();},createLinkPanel:function(){log("Returning Default panel");return this.defaultLinkPanel();
},defaultLinkPanel:function(){var f=new e.YUI2.widget.Panel("editorLinkPanelDiv"+this.id,{close:true,constraintoviewport:true,context:["editorEditRegion"+this.id,"bl","tl"],fixedcenter:false,modal:false,underlay:"shadow",visible:false,width:"45em"});
return f;},showLinkPanel:function(k){if(this.isPanelVisible(this.linkPanel)){return;}var i="editorLinkPanelDiv";
this.clearLinkInput();if(!this.linkPanel){this.linkPanel=this.createLinkPanel();var f=this.linkPanel.id,g=i+this.id;
if(f!=g){if(f.indexOf("wiki")>-1){i=f.replace(/\d+/,"");}else{var j=$(g);j.parentNode.removeChild(j);
}}this.linkPanel.hideEvent.subscribe(this.cancelLinkPanel,null,this);this.linkPanel.render();this.display(i);
this.linkPanel.align("bl","tl");this.bindZButton(this.linkPanel,"addLink","cancelLinkPanel");e.on("key",function(l){l.halt();
this.addLink();},"#"+this.linkPanel.id+" input","down:13",this);this.afterLinkPanelCreation();}var h;
if(this.hasSelectedText||this.hasSelectedImage){this.displayNone("editorLinkText");h=$("linkUrl"+this.id);
if(k){$("linkUrl"+this.id).value=k;}}else{this.display("editorLinkText");h=$("linkText"+this.id);}this.linkPanel.show();
h.focus();},addLink:function(j){if(j){j.halt();}if(!this.validateInputFields()){e.log("validateInputFields failed during addLink","error",this);
return;}var k=$("linkText"+this.id).value;var h=this.formatURL($("linkUrl"+this.id).value);var i=this.isZillowLink(h);
if(i){h=i;}var l=(i!==null);var f=false||l;var g=$("linkFollow"+this.id);if(g){f=g.checked||l;}this.insertZillowLink(h,k,f);
this.closeLinkPanel();},isZillowLink:function(f){if(!f){return null;}var h=/(^http(s)?:\/\/)?(www\.)?(zillow.com|zillow.local).*/i;
var g=f.match(h);if(g){if(f.indexOf("www")==-1){f=f.replace(/zillow/i,"www.$&");}return f;}return null;
},formatURL:function(f){return this.prefixProtocolToUrl(f);},prefixProtocolToUrl:function(f){if(f.indexOf("http:")!==0&&f.indexOf("https:")!==0){return"http://"+f;
}return f;},validateInputFields:function(){this.clearLinkInputErrors();var f=true;var g=$("linkUrl"+this.id);
if(g.value.length===0){Element.show("linkUrlError"+this.id);f=false;e.log("link url is empty","error",this);
}else{var j=["<object","<embed","<param"];var k=false;for(var h=0;h<j.length;h++){if(g.value.indexOf(j[h])>=0){k=true;
e.log("link url has invalid "+j[h],"error",this);}}if(k){Element.show("linkUrlFormatError"+this.id);f=false;
}}if($("editorLinkText"+this.id).style.display!="none"&&$("linkText"+this.id).value.length===0){Element.show("linkTextError"+this.id);
f=false;e.log("link text visible but empty","error",this);}return f;},cancelLinkPanel:function(){this.closeLinkPanel();
},closeLinkPanel:function(){if(!this.linkPanel){return;}this.linkPanel.hide();this.clearLinkInput();},clearLinkInput:function(){$("linkUrl"+this.id).value="";
$("linkText"+this.id).value="";this.clearLinkInputErrors();},clearLinkInputErrors:function(){Element.hide("linkTextError"+this.id);
Element.hide("linkUrlError"+this.id);Element.hide("linkUrlFormatError"+this.id);},doSave:function(g,f){log("RTE: doSave function not overridden, firing this.onSave");
this.onSave.fireEvent(g,f);},doEdit:function(){log("RTE: doEdit function not overridden, firing this.onEdit");
this.onEdit.fireEvent();},editorLoadComplete:function(){log("RTE: editorLoadComplete not implemented, firing this.onEditorLoadComplete");
this.onEditorLoadComplete.fireEvent();},afterLinkPanelCreation:function(){log("RTE: afterLinkPanelCreation not implemented, firing this.onAfterLinkPanelCreation");
this.onAfterLinkPanelCreation.fireEvent();},doCloseEditor:function(){log("RTE: doCloseEditor not implemented, firing this.onCloseEditor");
this.onCloseEditor.fireEvent();},onActionClick:function(g){g.halt();var f=g.currentTarget.get("href").split("#").pop();
if(f==="save"){this.save();}else{this.cancel();}},bindAnchorActions:function(f){var g=e.one("#"+(f?f+"-":"")+"action-buttons-"+this.id);
if(g){g.delegate("click",this.onActionClick,"a.inline-button",this);}},bindZButton:function(i,l,k,h){var j=h?i:this,f=e.Lang.isString,g=e.one("#"+i.id);
if(g){if(f(l)){l=j[l];}if(f(k)){k=j[k];}g.all(".action button").each(function(m){if(m.hasClass("primary")){m.on("click",l,j);
}else{m.on("click",k,j);}});}},getErrorMessage:function(h){var j=function(m){return h.indexOf(m)>-1;};
if(j("pottyMouthContent")){return"We're detecting inappropriate content. Please edit it.";}else{if(j("communityEditsDisabled")){return"Sorry, editing for pages is currently disabled.";
}else{if(j("invalidHtmlContent")){return"We're detecting invalid HTML content. Please edit it.";}else{if(j("noPermission")){return"You do not have permission to edit this content.";
}else{if(j("forbiddenLink")){return"It appears that your content includes links to inappropriate Web sites. Please delete the links.";
}else{if(j("uncategorizedError")){return"Sorry, we were unable to save your changes due to network problems. Please check your network settings and try again.";
}else{if(j("exceededSaveLimit")){return"You've reached the maximum number of pages you can edit today. Please try again tomorrow.";
}else{if(j("duplicatePageName")){return"The page title already exists. Please enter a different title.";
}else{if(j("invalidCharacterInPageName")){var l=h.indexOf("invalidCharacterInPageName")+"invalidCharacterInPageName".length+1;
var g=h.charAt(l);return"The character "+g+" is not allowed in page titles.";}else{if(j("invalidPageName")){var k=h.indexOf("invalidPageName")+"invalidPageName".length+1;
var i=h.indexOf(":endErrorMsg:");var f=h.substring(k,i);if(f=="nameTooShort"){return"The page title must be at least three characters long.";
}else{if(f=="nameTooLong"){return"The page title is too long. Please shorten your title to a maximum of 50 characters.";
}else{if(f=="invalidFirstCharacter"){return"The first character of a page title must be a letter.";}else{return"We could not add the page with the specified title. Please change your page title.";
}}}}else{if(j("contentTooLong")){return"The content is too long.  Please reduce the amount of text that you are submitting.";
}}}}}}}}}}}return null;},showErrorMessage:function(g){var f=$("richText-errors-"+this.id);f.innerHTML=g;
Element.show(f);},isPanelVisible:function(f){return !!(f&&f.cfg.getProperty("visible"));},displayNone:function(g){var f=$(g+this.id);
if(f){f.style.display="none";}else{log("cannot find element "+g+this.id);}},display:function(h,g){g=g||"block";
var f=$(h+this.id);if(f){f.style.display=g;}},makeVisible:function(g){var f=$(g+this.id);if(f){f.style.visibility="visible";
}},filterText:function(f){return f.replace(a.RE.unknownChar,"").replace(a.RE.smartDouble,'"').replace(a.RE.smartSingle,"'");
},filterImages:function(f){if(this.allowImages===false){e.log("BEFORE filterImages:\n"+f,c,this);var g=/(<|&lt;)img([^>]*)(>|&gt;)/gi;
if(g.test(f)){f=f.replace(g,"");this.editor.editorDirty=true;}e.log("AFTER filterImages: \n"+f,c,this);
}return f;},cleanPasteContent:function(f){f=f.replace(/<o:p>\s*<\/o:p>/g,"");f=f.replace(/<o:p>[\s\S]*?<\/o:p>/g,"&nbsp;");
f=f.replace(/\s*mso-[^:]+:[^;"]+;?/gi,"");f=f.replace(/\s*MARGIN: 0cm 0cm 0pt\s*;/gi,"");f=f.replace(/\s*MARGIN: 0cm 0cm 0pt\s*"/gi,'"');
f=f.replace(/\s*TEXT-INDENT: 0cm\s*;/gi,"");f=f.replace(/\s*TEXT-INDENT: 0cm\s*"/gi,'"');f=f.replace(/\s*TEXT-ALIGN: [^\s;]+;?"/gi,'"');
f=f.replace(/\s*PAGE-BREAK-BEFORE: [^\s;]+;?"/gi,'"');f=f.replace(/\s*FONT-VARIANT: [^\s;]+;?"/gi,'"');
f=f.replace(/\s*tab-stops:[^;"]*;?/gi,"");f=f.replace(/\s*tab-stops:[^"]*/gi,"");f=f.replace(/\s*face="[^"]*"/gi,"");
f=f.replace(/\s*face=[^ >]*/gi,"");f=f.replace(/\s*FONT-FAMILY:[^;"]*;?/gi,"");f=f.replace(/<(\w[^>]*) class=([^ |>]*)([^>]*)/gi,"<$1$3");
f=f.replace(/<(\w[^>]*) style="([^\"]*)"([^>]*)/gi,"<$1$3");f=f.replace(/<STYLE[^>]*>[\s\S]*?<\/STYLE[^>]*>/gi,"");
f=f.replace(/<(?:META|LINK)[^>]*>\s*/gi,"");f=f.replace(/\s*style="\s*"/gi,"");f=f.replace(/<SPAN\s*[^>]*>\s*&nbsp;\s*<\/SPAN>/gi,"&nbsp;");
f=f.replace(/<SPAN\s*[^>]*><\/SPAN>/gi,"");f=f.replace(/<(\w[^>]*) lang=([^ |>]*)([^>]*)/gi,"<$1$3");
f=f.replace(/<SPAN\s*>([\s\S]*?)<\/SPAN>/gi,"$1");f=f.replace(/<FONT\s*>([\s\S]*?)<\/FONT>/gi,"$1");f=f.replace(/<\\?\?xml[^>]*>/gi,"");
f=f.replace(/<w:[^>]*>[\s\S]*?<\/w:[^>]*>/gi,"");f=f.replace(/<\/?\w+:[^>]*>/gi,"");f=f.replace(/<\!--[\s\S]*?-->/g,"");
f=f.replace(/<(U|I|STRIKE)>&nbsp;<\/\1>/g,"&nbsp;");f=f.replace(/<H\d>\s*<\/H\d>/gi,"");f=f.replace(/<(\w+)[^>]*\sstyle="[^"]*DISPLAY\s?:\s?none[\s\S]*?<\/\1>/ig,"");
f=f.replace(/<(\w[^>]*) language=([^ |>]*)([^>]*)/gi,"<$1$3");f=f.replace(/<(\w[^>]*) onmouseover="([^\"]*)"([^>]*)/gi,"<$1$3");
f=f.replace(/<(\w[^>]*) onmouseout="([^\"]*)"([^>]*)/gi,"<$1$3");f=f.replace(/<H1([^>]*)>/gi,'<div$1><b><font size="6">');
f=f.replace(/<H2([^>]*)>/gi,'<div$1><b><font size="5">');f=f.replace(/<H3([^>]*)>/gi,'<div$1><b><font size="4">');
f=f.replace(/<H4([^>]*)>/gi,'<div$1><b><font size="3">');f=f.replace(/<H5([^>]*)>/gi,'<div$1><b><font size="2">');
f=f.replace(/<H6([^>]*)>/gi,'<div$1><b><font size="1">');f=f.replace(/<\/H\d>/gi,"</font></b></div>");
var g=new RegExp("(<P)([^>]*>[\\s\\S]*?)(</P>)","gi");f=f.replace(g,"<div$2</div>");f=f.replace(/<([^\s>]+)(\s[^>]*)?>\s*<\/\1>/g,"");
f=f.replace(/<([^\s>]+)(\s[^>]*)?>\s*<\/\1>/g,"");f=f.replace(/<([^\s>]+)(\s[^>]*)?>\s*<\/\1>/g,"");var h=new RegExp("["+String.fromCharCode(8220)+String.fromCharCode(8221)+"]","g");
f=f.replace(h,'"');return f;}};d.RichTextEditor=a;d.RichTextManager=(function(){var f={};function g(h){f[h.id]=h;
return h;}return{getEditor:function(h){return f[h]||null;},addEditors:function(h){e.log("deprecated, use addEditor","warn","RichTextManager");
return g(h);},addEditor:function(h){var i=new d.RichTextEditor(h);return g(i);}};})();},"3.1.0",{requires:["event-key","querystring-parse-simple","querystring-stringify-simple","zillow-imageupload","yui2-yahoo-dom-event","yui2-container","yui2-element"]});
YUI.add("email-a-friend-mgr",function(f){var g=null,j=null,d=null,c=5,h=2000,b=null,w=null,m=null,t=null,s=null,l="#email-alerts-menu",i="value",e="default-text",u=/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,y=new f.Z.SessionBeacon({idKey:"hdsdt",url:"/ajax/homedetail/HomeDetailSaveSessionState.htm"});
function x(z){this.SUBMITBUTTON=z.one("button.primary").removeClass("show");this.DUMMY=z.one("a.button-disabled");
}x.prototype={enable:function(){this.DUMMY.hide();this.SUBMITBUTTON.show();},disable:function(){this.DUMMY.show();
this.SUBMITBUTTON.hide();}};function k(z){this.emailFormWrapper=z;this.submitButton=new x(z);}k.prototype={hideAllErrors:function(){this.emailFormWrapper.all(".error").hide();
}};function q(B,E,z,D,A,C){this.el=B.addClass(e)||null;this.valid=true;this.maxlength=A||null;this.defaultValue=z||"";
this.errorEl=E||null;this.required=D||false;}q.prototype={constructor:q.prototype.constructor,hasEmptyValue:function(){return f.Lang.trim(this.el.get(i)).length===0;
},hasDefaultValue:function(){return this.el.get(i)===this.defaultValue;},isRequired:function(){return this.required;
},checkMaxLength:function(){if(this.el.get(i).length>this.maxlength){this.errorEl.show();return false;
}return true;},checkRequired:function(){if(this.isRequired()){if(this.hasEmptyValue()||this.hasDefaultValue()){this.errorEl.show();
return false;}}return true;}};function p(z){y.save("eafra",z);}function a(A){var E=A.el.get(i).split(/\s*,\s*|\s*;\s*/),D=Math.min(E.length,c),B,C=0;
for(;C<D;C++){B=E[C];if(B.length!==0){if(!u.test(B)){A.errorEl.show();return false;}}}if((E.length>c)){var z=f.Lang.trim(E[c]);
if(z.length===0){return true;}if(/[\w]+/.test(z)){A.errorEl.show();return false;}}return true;}function v(B,A){var z=B.currentTarget;
if(A.hasEmptyValue()&&A.defaultValue!==""){z.set(i,A.defaultValue);z.addClass(e);}else{if(A.hasDefaultValue()){z.set(i,"");
z.removeClass(e);}}}function n(A,z){v(A,z);if(!z.valid){if(z===w){z.valid=z.checkRequired();}else{if(z===b||z===m){z.valid=z.checkRequired()&&a(z);
}else{if(z===t){z.valid=z.checkMaxLength();}}}if(z.valid){z.errorEl.hide();}}}function r(z){f.each(z,function(A){A.el.on("blur",n,this,A);
A.el.on("focus",v,this,A);},this);}var o={validateForm:function(z){j.hideAllErrors();if(s!==null){d.one("#eplink").set(i,s);
}b.valid=b.checkRequired()&&a(b);w.valid=w.checkRequired();m.valid=m.checkRequired()&&a(m);t.valid=t.checkMaxLength();
if(b.valid&&w.valid&&m.valid&&t.valid){g.config.addParams={remail:b.el.get(i),sname:w.el.get(i),semail:m.el.get(i),smsg:t.el.get(i),sts:d.one("#sts").get("checked"),eplink:d.one("#eplink").get(i)};
j.submitButton.disable();g.doChange(z);}else{z.halt();return false;}},init:function(E,B,z){s=z;if(g===null){g=new LightboxAjaxDialog("email-a-friend",null,{onSubmit:this.validateForm});
var D=g.lightbox.dialog;if(!D._node){D=f.one(D);}D.setStyle("top","50px");D.addClass("email-a-friend");
}g.confirm();if(B){f.fire("trackLink",B,"Send to Friend",{events:"event20"});}if(f.one(".emailafriend-lightbox")!==null){d=f.one(".emailafriend-lightbox form");
j=new k(d);j.submitButton.enable();var F=d.one("#remail"),C=d.one("#sname"),G=d.one("#semail"),A=d.one("#smsg");
if(!E){F.set(i,"Up to 5 recipient e-mails");}else{if(f.one(l)){F.set(i,f.one(l).one(".default-email-ids").get("text"));
}else{if(f.one(".default-email-ids")){F.set(i,f.one(".default-email-ids").get("text"));}}}b=new q(F,d.one(".remail-error"),"Up to 5 recipient e-mails",true);
w=new q(C,d.one(".sname-error"),"John Doe",true);m=new q(G,d.one(".semail-error"),"Your e-mail",true);
t=new q(A,d.one(".smsg-error"),A.get(i),false,h);r([b,w,m,t]);if(m.defaultValue!==G.get(i)){m.el.removeClass(e);
}if(E&&b.defaultValue!==G.get(i)){b.el.removeClass(e);}}},handleSuccess:function(){var z=b.el.get(i),A=f.one(l);
if(A){A.one(".default-email-ids").set("text",z);if(A.one(".default-ids")){A.one(".default-ids").show();
}}p(z);}};f.namespace("Z").EmailAFriendMgr=o;f.config.win.EmailAFriendManager=o;},"3.3.0",{requires:["zillow-session-beacon","zillow-node-methods","omniture-tracking"]});
YUI.add("share-on-facebook",function(d){var a=new d.Z.ShareOn.Base({selector:".fb_share",shareURL:"http://www.facebook.com/sharer.php?",trackingEvent:"event21",trackingId:"Share on Facebook"});
function c(e,g,f){a.share({u:e,t:g,src:f});}function b(g){var f=g.node;c(f.getAttribute("href"),f.getAttribute("shareMessage")||d.config.doc.title,"sp");
}a.doShare=c;a.on("share",b);d.Z.ShareOn.Facebook=a;},"3.3.0",{requires:["share-on-base"]});
YUI.add("share-on-twitter",function(b){function a(c){c.target.share({status:c.node.getAttribute("longdesc")});
}b.Z.ShareOn.Twitter=new b.Z.ShareOn.Base({selector:".share-on-twitter",shareURL:"http://twitter.com/home?",trackingEvent:"event31",trackingId:"Share on Twitter",on:{share:a}});
},"3.3.0",{requires:["share-on-base"]});
YUI.add("share-on-base",function(b){function a(c){a.superclass.constructor.apply(this,arguments);}b.namespace("Z.ShareOn")["Base"]=b.extend(a,b.Base,{initializer:function(c){this.publish("share",{emitFacade:true,defaultFn:this._trackShare,preventable:false});
b.on("load",b.bind(this._onLoad,this));},share:function(d){var c=this.get("shareURL")+b.QueryString.stringify(d);
b.config.win.open(c,this.get("windowName"),this.get("windowConfig"));},_onLoad:function(){var c=this.get("selector");
if(c){b.all(c).on("click",this._onClick,this);}},_onClick:function(c){c.halt();this.fire("share",{node:c.target});
},_trackShare:function(g){var d=g.node,c=d.getAttribute("location"),f={events:this.get("trackingEvent")};
if(c){f.eVar4=c;}b.fire("trackLink",b.Node.getDOMNode(d),this.get("trackingId"),f);}},{NAME:"shareOn",ATTRS:{selector:{validator:b.Lang.isString},shareURL:{value:""},trackingEvent:{value:""},trackingId:{value:""},windowName:{value:"sharer"},windowConfig:{value:"toolbar=0,status=0,width=626,height=436"}}});
},"3.3.0",{requires:["base-base","node-base","querystring-stringify-simple","omniture-tracking"]});YUI.add("social-sharing",function(){},"3.3.0",{use:["share-on-base","share-on-facebook","share-on-twitter"]});
YUI.add("profile-aboutme-manager",function(g){var c=g.config.win;function b(l){var j=g.one("#profile-aboutme-viewRegion"),i=g.one("#profile-aboutme-editRegion");
if(l){j.hide();i.show();g.one("#throbber").hide();try{g.Z.RichTextManager.getEditor("aboutMeTextArea").edit();
}catch(k){g.log(k.message,"error");}}else{i.hide();j.show();}}c.toggleEdit=b;function e(o,i,k){var n=i.responseXML.getElementsByTagName("Response")[0],m=n.getElementsByTagName("div"),l=m[1],j=m[2];
if(!l.firstChild){l=g.one("#empty-aboutme").getContent();j="";}else{l=l.firstChild.nodeValue;j=j.firstChild.nodeValue;
}g.one("#profile-aboutme-content").setContent(l);this.saveSuccessful(l,j);}function f(m,i,j){var l=i.responseXML.getElementsByTagName("Response")[0],k=l.getElementsByTagName("div")[0].firstChild.nodeValue;
this.saveFailed(k);g.one("#throbber").hide();}function a(j,i){if(!i){this.saveSuccessful();g.log("no changes made!");
return;}g.one("#throbber").show();g.io("/user/ProfileSaveContent.htm",{method:"POST",context:this,data:{saveType:"aboutMe",saveValue:j,contextid:this.contextId},"arguments":{saved:j},on:{success:e,failure:f}});
}g.on("editor:loaded",function h(i){var j=i.id;if(j!=="aboutMeTextArea"){return;}g.log("loaded aboutMeTextArea","info","ProfileAboutMeManager");
i.onSave.subscribe(a,i);i.bindAnchorActions();i.doCloseEditor=function(){g.one("#throbber").hide();b(false);
};i.doEdit=function(){i.focusEditor(true);};});function d(i){var k="hide",j="show";g.all("#wikicontribution-expand, #collapseWikiLink")[i?k:j]();
g.one("#expandWikiLink")[i?j:k]();return false;}c.toggleWikiContributions=d;},"3.3.0",{requires:["zillow-node-methods","io-base","querystring-stringify-simple"],optional:["zillow-richtexteditor"]});
var Review=(function(){var b="review_";var d="rebuttal_";var m="rebuttalToggleArea_";var c="respondLink_";
var n="displayButton_";var g="delete_";var e="deleteReviewLink_";var l="respondForm_";var k="submitButton_";
var f="cancelButton_";var j="response_";var i="params_";var a="rebuttalText_";function h(o,p){var q=o.id;
return q.replace(p,"");}return{respond:function(p){var o=h(p,c);Element.show(d+o);Element.show(l+o);Element.hide(c+o);
$(a+o).innerHTML="";},submit:function(q){var o=h(q,k);var s=s||$(i+o).value;var p=$Y.QueryString.stringify({rebuttal:$(j+o).value,type:1});
p=p+"&"+s;var r=document.forms[l+o];$Y.io(r.action+"?"+p,{method:"GET",on:{success:function(x,t){try{var w=t.responseText.replace(/<!--.*$/,"");
var v=$Y.JSON.parse(w);if(v.error){throw new Error(v.error);}$(a+o).innerHTML=$(j+o).value;Element.hide(l+o);
Element.show(g+o);Element.show(n+o);}catch(u){alert(u.message);}},failure:function(u,t){$(a+o).innerHTML="There was a problem.";
}}});},cancel:function(o){var p=h(o,f);Element.hide(d+p);Element.show(c+p);},remove:function(q,r){var o;
if(r==3){o=h(q,e);}else{o=h(q,g);}var t=t||$(i+o).value;var p=$Y.QueryString.stringify({rebuttal:"",type:r});
p=p+"&"+t;var s=document.forms[l+o];$Y.io(s.action+"?"+p,{method:"GET",on:{success:function(v,u){$(a+o).innerHTML="Your response was deleted.";
Element.hide(g+o);Element.hide(l+o);Element.show(c+o);Element.hide(n+o);if(r==3){Element.hide(b+o);}},failure:function(v,u){$(a+o).innerHTML="There was a problem.";
Element.hide(l+o);}}});},toggleRebuttal:function(p){var o=h(p,n);Element.toggle(m+o);var q=$Y.one(p);
if(q.hasClass("contracted")){q.replaceClass("contracted","expanded");}else{q.replaceClass("expanded","contracted");
}},deleteReview:function(o){alert("here, let me get that for you");}};})();
var NextStepsContactFormManager=function(){var b;var a;return{setupInlineForm:function(){NextStepsFormFactory.create("#next-steps-inline-form","next-steps-inline-form",false);
},setupcColForm:function(){NextStepsFormFactory.create("#cCol-contact-lender","cCol-contact-lender",false);
},setupMobileForm:function(){NextStepsFormFactory.create("#next-steps-inline-form","cCol-contact-lender",true);
},setupcColFormAlt:function(){NextStepsFormFactory.create("#cCol-contact-lender-alt","cCol-contact-lender-alt",false);
},setupLightboxForm:function(){var c=$Y.one("#next-steps-lightbox");a=c.one(".background");b=NextStepsFormFactory.create(c,"next-steps-lightbox",false);
c.all("a.close, .cancel-button").on("click",NextStepsContactFormManager.hideLightbox);$Y.on("key",function(f){f.halt();
},c,"down:13");var d=c.one("div.phone");if(d){d.delegate("keypress",function(f){if(f.keyCode>90){f.halt();
}},"input");}},trackLenderWebsiteClick:function(c,d){b.updateActionLocation(c);if(d){b.updateReferenceData(d);
}b.trackWebsiteClick();},showLightbox:function(c,d){b.updateActionLocation(c);if(d){b.updateReferenceData(d);
}$Y.one("body").addClass("lightboxed");b.show();if($Y.UA.ie&&$Y.UA.ie==6){window.scroll(0,0);a.setStyles({width:$Y.DOM.docWidth(),height:$Y.DOM.docHeight()});
}log("show lightbox");},hideLightbox:function(c){if(c){c.halt();}$Y.one("body").removeClass("lightboxed");
b.hide();}};}();var NextStepsFormFactory=(function(){function d(p){return $Y.one(p).one("div").get("hiddenBlockJSON");
}function k(p){$Y.Object.each(p,function(q){if(q){q.hide();}});}function c(p,q){p.hide("fadeOut",{delay:(q||2)});
}function e(t,r,x,v,w,q){var u=t.target;var p=u.ancestor("li");r.removeClass("selected");p.addClass("selected");
if(x.hasClass("default")||x.get("value").length<2){var s=p.one(".hide");log("Hidden Element Content: ",s._node.innerHTML);
if(s.hasClass("custom")){w.set("innerHTML",s.get("innerHTML"));q.setStyle("visibility","hidden");x.hide();
v.hide();w.show();}else{x.set("value",s.get("innerHTML"));w.hide();x.show();v.show();q.setStyle("visibility","visible");
}x.addClass("default");}}function b(H,M,y,q,z,B,D,L,u,p,G,A,w,J,K,F,x,E,C,v){H.halt();var N=H.target;
if(N.hasClass("disabled")||N.ancestor(".disabled")!==null){return;}var r=q.one("p.message-error-container");
if((D.hasClass("default")&&!D.hasClass("mobile-default"))||D.get("value").length<5){r.set("text","Please fill in a note to the lender (5 character minimum).");
r.removeClass("hide");return;}var t=q.all("input.required").some(function(O){if(O.get("value")==""||O.hasClass("placeholder")){q.one("p.error").set("text","Please fill out all form fields.").show();
return true;}});if(t===true){return;}if(G&&G.isInProgress()){return;}k(L);var I=d(y);var s=f(M,I,z,B,D,A,w,J,K,F,x,E,C);
G=$Y.io(s,{on:{success:function(P,O){l(O,L,u,p,I,M,s,q,v);},failure:function(){o(L,u);}}});}function f(p,B,u,r,x,D,y,s,E,q,t,w,F){var v={};
v.m=x.get("value");v.ea=r.get("value");v.eli=B.requiredData.encodedProfessionalId;if(D){v.n=D.get("value");
}if(y){v.fn=y.get("value");}if(s){v.ln=s.get("value");}if(E){v.fp=E.get("value");}if(q){v.ac=q.get("value");
}if(t){v.p=t.get("value");}if(w){v.pn=w.get("value");}if(F){v.e=F.get("value");}var A=p.submitConfig,C=A.submitUrlParams;
if(C){$Y.Object.each(C,function(H,G){var I=B.additionalData[H];if(I){v[G]=I;}});}var z=A.submitUrl+"?"+$Y.QueryString.stringify(v);
log("submit url",z);return z;}function l(t,y,v,u,x,p,r,s,q){var z=$Y.JSON.parse(t.responseText);log(z,y,v,u);
if(z.success){if(u){u.show();if(v!==null){v.hide();}else{c(u,4);}}(new Image()).src="http://ad.yieldmanager.com/pixel?id=1184480&id=1184481&t=2";
if(q==false){setTimeout(function(){g(r,s,x.trackingConfig,z);},250);}else{var w=a(s);if(!w){w="unknown";
}window.location.href="zillow://analytics/event/contact/email/"+w+"/1";}}else{if(z.errors){if(z.errors.ea){y.addressError.set("text",z.errors.ea);
y.addressError.show();}if(z.errors.m){y.messageError.set("text",z.errors.m);y.messageError.show();}if(z.errors.fn){y.nameError.set("text",z.errors.fn);
y.nameError.show();}if(z.errors.pn){y.phoneError.set("text",z.errors.pn);y.phoneError.show();}}else{y.genericError.show();
c(y.genericError,4);}}}function o(p,q){p.genericError.show();c(p.genericError,4);}function j(q){var p=q.target;
if(p.hasClass("default")&&!p.hasClass("mobile-default")){p.set("value","");p.removeClass("default");}if(q.keyCode==27){q.halt();
}}function n(r,p){var q={events:"event36",eVar4:a(r)};if(p){i(q,p);}trackLink({action:r},"ZMM Lender website click",q);
(new Image()).src="http://ad.yieldmanager.com/pixel?id=1184478&id=1184479&t=2";}function h(r,p){var q={events:"event27",eVar4:a(r)};
if(p){i(q,p);}trackLink({action:r},"ZMM Contact lightbox show",q);}function g(r,t,p,q){var s={events:"event28",eVar4:a(t),eVar6:q.type};
if(p){i(s,p);}trackLink({action:r},"ZMM Contact form submit",s);}function i(q,p){q.eVar21=m(p.so,p.sa);
q.eVar22=p.qp;q.eVar23=p.rs;q.eVar24=p.li;q.eVar25=p.lr;}function m(p,q){return q?p+"-asc":p+"-dsc";}function a(p){return $Y.Lang.trim(p.one(".action-location").get("innerHTML"));
}return{create:function(p,H,Y){log("create form wrapper",p);p=$Y.one(p);var P=p.one(".emailAddress");
var E=p.one("textarea");var I=p.one(".textarea-heading");var S=p.one(".custom-action-area");var R=p.one(".submit-area");
var w=p.one(".name");var V=p.one(".fname");var C=p.one(".lname");var N=p.one(".fullPhone");var r=p.one(".areaCode");
var O=p.one(".prefix");var s=p.one(".phoneNumber");var D=p.one(".extension");var G=p.one(".signature-area");
var T=p.one(".external-link-option"),F,Z;if(T){F=T.one("a.external-link");Z=T.one("input.external-link");
}var x=p.one(".default-selection");var v,t;if(H==="next-steps-lightbox"){v=p.one(".entry-area");t=p.one(".success-area");
}else{v=null;t=p.one(".next-steps-success-message");}var q={success:p.one(".next-steps-success-message"),messageError:p.one(".message-error-container"),nameError:p.one(".name-error-container"),phoneError:p.one(".phone-error-container"),addressError:p.one(".emailAddress-error-container"),genericError:p.one(".generic-error-container"),generalValidationError:p.one(".general-validation-error")};
var M=p.all("ul.radio-buttons li");var U=function(ab){e(ab,M,E,I,S,R);};var J=p.all(".radio-buttons li input");
J.on("click",U);J.some(function(ab){var ac=ab.ancestor("li");if(ac.hasClass("selected")){ab.set("checked",true);
return true;}});var z=null;var L=d(p.one(".submit-configuration"));var A=p.one(".reference-data");E.on("focus",j);
var W=function(ab){b(ab,L,A,p,M,P,E,q,v,t,z,w,V,C,N,r,O,s,D,Y);};p.one("button.submit-button").on("click",W);
p.on("submit",W);var y=p.one(".action-location");var X=function(ab){y.set("innerHTML",ab);};var Q=function(ab){var ac=document.createElement("div");
ac.className="hide";ac.appendChild(document.createComment($Y.one(ab).get("hiddenBlock")));A.innerHTML="";
A.appendChild(ac);log(d(A));};var aa=function(){p.hide();};var K=function(){k(q);v.show();t.hide();var ac=d(A),ag=ac.additionalData.signatureElementId;
if(ag&&$Y.one(ag)){G.set("innerHTML",$Y.one(ag).get("innerHTML"));}else{G.set("innerHTML","");}if(ac.requiredData.isExternalLinkAvailable){var af={};
for(var ad in L.externalLinkConfig.trackingUrlParams){var ae=L.externalLinkConfig.trackingUrlParams[ad];
var ab=ac.additionalData[ae];if(ab){af[ad]=ab;}else{af[ad]=ae;}}if(F){F.href=L.externalLinkConfig.trackingUrl+"?"+$Y.QueryString.stringify(af);
}if(T){T.show();}}else{if(Z&&Z.get("checked")){x.set("checked",true);}if(T){T.hide();}}if($Y.DOM.winHeight()<700){p.one(".dialog").setStyle("top","10px");
}p.show();setTimeout(function(){h(p,ac.trackingConfig);},250);};var u=function(){var ab=d(A);n(p,ab.trackingConfig);
};var B={updateActionLocation:X,updateReferenceData:Q,hide:aa,show:K,trackWebsiteClick:u};log("formCallbacks");
log(B);return B;}};}());
YUI.add("zillow-profile-review",function(c){var i=1,o=2,j=3;function f(q){if(!q){return null;}return c.one("#review-"+q);
}function p(r){if(!r){return null;}var q=f(r).one("input[name=requestUrl]"),s="";if(q){s=q.get("value");
}return s;}function n(q){if(!q){return false;}var s=f(q).one("input[name=isLenderReview]"),r=false;if(s&&s.get("value")!==null&&s.get("value")==="true"){r=true;
}return r;}function g(){var r=c.config.win,q=r.location.href.split("?"),t=q[0],u,s;if(q.length>1){q[1]=q[1].replace("#","");
u=c.QueryString.parse(q[1]);s=t+"?"+c.QueryString.stringify(u);}else{s=r.location.href.replace("#","");
}c.log("currLoc :"+s);r.location=s;}function e(q,r){var t=f(q),s=null;if(!t){return;}s=t.one(".submission-error-messaging");
s.addClass("error").one(".message").setContent(r);s.show().transition({opacity:{value:0},delay:2},function(){this.hide();
this.setStyle("opacity",1);});}function m(r){var q=f(r),s=q.one(".rebuttal-form"),u=q.one(".response-container"),t=u.one(".response-text"),v=q.one(".edit-response");
s.hide();if(t.get("text")===null||c.Lang.trim(t.get("text"))===""){u.hide();q.one(".respond-review").show();
if(v){v.hide();}q.one(".delete-response").hide();}else{u.show();q.one(".respond-review").hide();if(v){v.show();
}q.one(".delete-response").show();}}function b(s){var q=f(s.getAttribute("reviewid")),t=q.one(".rebuttal-form"),r=t.one(".response-input-text"),u=q.one(".response-container");
s.hide();if(s.hasClass("edit-response")){q.one(".delete-response").hide();}u.hide();t.show();if(c.Plugin.AttrPlaceholder.SUPPORTED===false){r.focus();
r.blur();}}function a(q){q.halt();b(q.currentTarget);}function h(u){u.halt();if(!confirm("Are you sure you want to delete this response?")){return;
}var v=u.currentTarget,r=v.getAttribute("reviewid"),q=f(r),s=q.one(".rebuttal-form .response-input-text"),t={};
if(n(r)){t={rebuttal:"",type:o};}else{t={reviewId:r,updateType:o};}c.io(p(r),{data:t,on:{success:function(z,w){var y;
try{y=c.JSON.parse(w.responseText);}catch(x){e(r,"Your response could not be deleted. Please try again later.");
c.log("Couldn't parse json response - "+x,"error","ProfileReview.deleteResponse");return;}if(!y){e(r,"Your response could not be deleted. Please try again later.");
return;}else{if(y.error){e(r,y.error);return;}}q.one(".response-container .response-text").setContent("");
s.set("value","");m(r);},failure:function(x,w){e(r,"Your response could not be deleted. Please try again later.");
}}});}function l(t){var q=t.currentTarget.getAttribute("reviewid"),x=f(q),w=x.one(".rebuttal-form"),y=w.one(".response-input-text"),r=y.get("value"),u=x.one(".response-container"),v=u.one(".response-text"),s={};
if(r!==null&&c.Lang.trim(r)!==""&&c.Lang.trim(r)!==y.getAttribute("placeholder")&&c.Lang.trim(r).length<=1000){if(n(q)){s={rebuttal:c.Lang.trim(r),type:i};
}else{s={reviewId:q,updateType:i,rebuttal:c.Lang.trim(r)};}c.io(p(q),{method:"POST",data:s,on:{success:function(C,z){var A;
try{A=c.JSON.parse(z.responseText);}catch(B){e(q,"Your response could not be submitted. Please try again later.");
c.log("Couldn't parse json response - "+B,"error","ProfileReview.submit");return;}if(!A){e(q,"Your response could not be submitted. Please try again later.");
return;}else{if(A.error){e(q,A.error);return;}}v.set("text",r);m(q);},failure:function(A,z){e(q,"Your response could not be submitted. Please try again later.");
}}});}else{if(c.Lang.trim(r).length>1000){e(q,"Your response can not be more then 1000 characters.");
}else{e(q,"Your response can not be blank. Please enter some text.");}}}function d(t){t.halt();if(!confirm("Are you sure you want to delete this review?")){return;
}var r=t.currentTarget.getAttribute("reviewid"),q=f(r),s={};if(n(r)){s={rebuttal:"",type:j};}else{s={reviewId:r,updateType:j};
}c.io(p(r),{data:s,on:{success:function(x,u){var w;try{w=c.JSON.parse(u.responseText);if(!w){e(r,"Your review could not be deleted. Please try again later.");
return;}if(w.error){e(r,w.error);return;}q.transition("fadeOut",{delay:0.5},function(){this.remove();
});}catch(v){e(r,"Your review could not be deleted. Please try again later.");c.log("Couldn't parse json response - "+v,"error","ProfileReview.deleteReview");
return;}},failure:function(v,u){e(r,"Your review could not be deleted. Please try again later.");}}});
}function k(s){s.halt();var u=s.currentTarget,r=u.getAttribute("reviewid"),t=u.getAttribute("statusid"),q=f(r);
c.io("/ajax/profiles/UpdateReviewModerationStatus.htm",{data:{reviewId:r,statusId:t},on:{success:function(y,v){var x;
try{x=c.JSON.parse(v.responseText);if(!x){e(r,"Review could not be queued for 2nd opinion. Please try again later.");
return;}if(x.error){e(r,x.error.message);return;}q.transition("fadeOut",{delay:0.5},function(){this.remove();
});g();}catch(w){e(r,"Review could not be queued for 2nd opinion. Please try again later.");c.log("Couldn't parse json response - "+w,"error","ProfileReview.moderateReview");
return;}},failure:function(w,v){e(r,"Review could not be queued for 2nd opinion. Please try again later.");
}}});}c.namespace("Z").ProfileReview=c.Base.create("profileReview",c.Widget,[],{CONTENT_TEMPLATE:null,initializer:function(){c.on("load",c.bind(this.render,this));
},bindUI:function(){var r=this.get("boundingBox");r.all(".respond-review, .edit-response").on("click",a);
r.all(".delete-response").on("click",h);r.all(".delete-review").on("click",d);r.all(".second-opinion").on("click",k);
var q=r.one(".rebuttal-form");if(q){q.one("button.primary").on("click",l);q.one("button.cancel").on("click",function(s){m(s.currentTarget.getAttribute("reviewid"));
});}},syncUI:function(){this._respondToHash();},_respondToHash:function(){var t=this.get("boundingBox"),s=c.config.win.location.href.split("#"),q,r;
if(s.length>1){q=c.QueryString.parse(s[1]);if(q.hasOwnProperty("respond")){r=t.one(".rebuttal a.respond-review");
if(r&&!r.hasClass("hide")){b(r);return;}r=t.one(".rebuttal a.edit-response");if(r&&!r.hasClass("hide")){b(r);
}}}}},{ATTRS:{reviewId:{writeOnce:true},requestUrl:{},isLenderReview:{}},HTML_PARSER:{reviewId:function(q){return q.get("id").replace("review-","");
},requestUrl:function(q){var s="",r=q.one("input[name=requestUrl]");if(r){s=r.get("value");}return s;
},isLenderReview:function(q){var s=false,r=q.one("input[name=isLenderReview]");if(r){s=(r.get("value")==="true");
}return s;}}});},"3.3.0",{requires:["base-build","widget-uievents","widget-htmlparser","html5-attr-placeholder","zillow-hash-reader","node-event-simulate","querystring-parse-simple","querystring-stringify-simple","io-base","json-parse"]});
(function(){var b={defaultFilterId:1,defaultSortId:4};function a(){$Y.on("contentready",this.init,"#c-column",this);
}a.prototype={constructor:a.prototype.constructor,toString:function(){return"[ProfileTemplate]";},onSortChange:function(g){var d=this.currentURL.split("?");
var f=parseInt($Y.one("#reviews-filters").get("value"),10);var c=parseInt($Y.one("#reviews-sorts").get("value"),10);
d[1]=$Y.QueryString.stringify({s1:f,s2:c});d[0]=d[0].replace(/\/$/,"");d=d.join("?");window.location=d;
},init:function(){this.currentURL=$Y.Lang.trim($Y.one("#reviews-current-url").get("hiddenBlock"));$Y.one("#reviews-filters").on("change",this.onSortChange,this,true);
$Y.one("#reviews-sorts").on("change",this.onSortChange,this,true);}};ZILLOW.namespace("module.Review").Browse=a;
})();
